const AboutUs = () => {
    return (
        <>
            <div className='container'>
                <div className="bg-white rounded-md mt-3 shadow border-round px-4 py-2.5 text-slate-400">
                    <h1>About Us</h1>
                    <p>Hello, Dear friends, Welcome to sipcalculatorai also, we are happy you want to know something more about our site</p>
                    <p>So, basically, nowadays people are more dependent on online products and services that's why we also, take forward a step to help you.</p>
                    <p>Our first wish is to provide you with a better solution to solve your problem. So, kindly if you don't get any solution then mention it in the comment section.</p>
                    <p>Also, we are trying to provide fresh & latest content that provides you ideas about all updated information that's happening in the world.</p>
                    <p>In the below section you can get more ideas about our site like our website category and content category.</p>
                    <p>If you have additional questions or require more information about our About Us Page, do not hesitate to contact us through email at  <span className="text-[1.3rem]"><b>thesipcalculator@gmail.com
                    </b></span></p>
                    <h2><b>What is Our Goal?</b></h2>
                    <p>There are millions of websites created every day, also, there is much fake content spread on the internet.</p>
                    <p>So, Our main goal is to provide you with 100% Original and Safe content that provides you a great and better experience on the world wide web.</p>
                    <p>We mainly focus on our service so and improving it regularly to provide a better user experience to all users.</p>
                    <p>Basically, we focus on the finance niche so, our main priority is to search for new content and present it in front of you to learn something new. </p>
                    <h3><b>What is our Service?</b></h3>
                    <p>We are mainly focused on the finance category so, we provide finance related content if you are interested in the finance category then you can visit daily to get more latest information.</p>
                    <p>sip calculator</p>
                    <p>On our website sipcalculatorai you get can all finance related information also, we focus on many other categories and we hope you like also, the content of other categories that are maintained on our website. So, you can visit our website homepage to know all category details here you can visit our homepage Click here sipcalculatorai.</p>
                    <p>Also, we provide a Notification update service you can join by email and other Social Media Platforms, and all Links you can get on the Homepage visit now. sipcalculatorai</p>
                    <h3><b>About sipcalculatorai</b></h3>
                    <p>As you can see already we mention what is our goal and Service again we repeat that we mainly focus on finance Category to help people.</p>
                    <p>This Website is Created By sipcalculatorai to help people because many people are still spending hours of time to get exact information so, this is the only motive to create sipcalculatorai to help people and provide them a better web experience. Also, This About Us Page is Generated With Soumya help.</p >
                    <p>Now, the time is to know about the Admin Details of this website, so, now we have to go down to know about Admin details.</p>
                    <h3><b>Admin's Statement for sipcalculatorai</b></h3>
                    <p>As per my point of view, there are many people who visit the internet to get some information but 90% of the time they get wrong information so, the first priority of our website sipcalculatorai is to provide 100% legit and accurate information to our users, Also, I hope my dream comes true one day, and our website will provide Original Content to provide a better user experience. So, From my Side thanks for visiting our website.</p>
                    <h3><b>Admin's Contact Information</b></h3>
                    <p>Hi, this manish arora, in the above paragraph you know about the website properly and now I am going to provide my contact details.</p>
                    <p>If you have any problem & suggestions for this website then you can contact me by using following contact details.</p>

                    <p>These details are my personal Account details if you want to contact me then you can contact me by the above platform.</p>
                    <p>Finally, this is our complete about us page about details are showing what is the motive to create sipcalculatorai. Also, this page is generated by Soumya Help About Us Generator</p>
                    <p>If you want to contact us then you can email us at thesipcalculator@gmail.com
                        also, you can contact us by our contact us form. Go to homepage sipcalculatorai</p>
                    <center>
                        <p>"Thanks for visiting our About Us Page"</p>
                    </center>

                </div >
            </div >
        </>
    )
}

export default AboutUs;